### ISSUE TITLE
VNC Console - Unexpected Behavior - 

### ISSUE THREAD

**Issue by Wizlonex** [cockpit-project/cockpit-machines#1522]
Hi I have some 'unexpected behavior' of the VNC console in the virtual machines plugin that I would like to report.

How to reproduce:

From cockpit interface of server1 create and start a vm (leave it running). Now select a different cockpit host machine from the host menu cockpit interface (assumed to be server2), which should log you into server2's cockpit portal.  Open a running vm in server2 and view the console.

Expected behavior:  The console opens for the vm on server2

Actual behavior:  The console opens for the vm on server1, even though you are viewing the portal of cockpit on server2.

I am not a programmer, but I think that server1 is not using the correct console address for the vm on server2, and so it connects to either localhost:590x or perhaps server1:590x for console access instead of server2:590x?

I don't know the right way to fix this or even if it needs to be 'fixed'.  It's still perfectly usable if you access consoles only directly from cockpit portals (i.e. not as aded-hosts) for the server hosting the vm (or via e.g. virt-manager). 

I am seeing this behavior with cockpit installed on Debian12 servers, and it can be reproduced (at least by me) with any servers I connect with as added-hosts to the server1 cockpit interface.  I can provide system info if needed, but hopefully this is somewhat self-explanatory?

I have a short video that might make it easier to understand this unexpected behavior in case my explanation is unclear.

https://github.com/cockpit-project/cockpit-machines/assets/35621692/11be957e-ef03-4619-a322-ef81b6605bd2

THANK YOU for the excellent plugin.

Andrew

**Comment by mac2net** [comment]
Only time I saw this was with nested VMs and issues with the different subnets. 
I suggest testing this with Virtual Machine Manager inside a DE on the server accessed through VNC. You can do this with nested VMs. I did this just yesterday.

**Comment by jelly** [comment]
Which version of Cockpit is this? This was fixed in https://github.com/cockpit-project/cockpit-machines/commit/6024303e1030fc196ac7ecc86c4a532edd9294e2 which ended up in Cockpit-machines 303.

**Comment by Wizlonex** [comment]
I am running the normal install, not backports so that more than explains it.  Being as you are aware of this and taken action I think that's more than enough.  I will close this thread out with my apologies for pinging you (I did search for this prior to posting but never got a hit, sorry).  

I will navigate around this minor issue until I eventually upgrade - it's not a big deal, I just thought it was weirdly cool at least.

Again, THANK YOU for an EXCELLENT plugin.  It is totally brilliant.  Have a great day!

Andrew

**Comment by martinpitt** [comment]
@Wizlonex No worries, please let us know if it still doesn't work with the latest version. Cheers!

**Comment by Wizlonex** [comment]
Hi:

Ok, so I upgraded one of my servers to run the backports version, I apt-installed cockpit and cockpit-machines (for good measure), restarted cockpit and confirmed the versions:

cockpit is already the newest version (311-1~bpo12+1).   #Upgraded
cockpit-machines is already the newest version (288-1).  #Same as default package

 and...the issue is still there.

If I add a host that runs the OLD cockpit version then it still shows me the wrong console in cockpit-machines
If I add the upgraded host to a server running the default cockpit version then...it also still shows the wrong console
What I haven't done is upgraded cockpit on my other machines as I don't really want to do that right now, but I'm not sure I expect that to work now either?

So, it would seem it's not fixed at my end at least.  I can create a video showing this if it's useful, but it's essentially the same as the one before.  I still don't think this is a big deal, but the least I can do is to provide anything you need if it's useful.

Thanks and sorry to bring a dead-bug back to life!

Andrew

**Comment by martinpitt** [comment]
@Wizlonex 288-1 is the released version, see https://tracker.debian.org/pkg/cockpit-machines . Backports has 309.

**Comment by Wizlonex** [comment]
Ok, I am on travel on other business so it will take me a few days but I will post back to confirm it works using both the updated cockpit and cockpit-machines packages.

**Comment by Wizlonex** [comment]
HI.  Back from travels.  I installed the backports versions on my server and it does indeed fix the issue, so it's a specific artifact with the older versions that are installed as standard in bookworm.  Please close this out with my sincere thanks for your time and again for your excellent plugin.

Andrew

**Comment by martinpitt** [comment]
@Wizlonex Happy to hear it works for you now!
